# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["USER_NAME"] %>
  password: <%= ENV["PASSWORD"] %>
  port: 5432

development:
  <<: *default
  database: <%= ENV['POSTGRES_DEV_DB'] %>
  username: <%= ENV["USER_NAME"] %>
  password: <%= ENV["PASSWORD"] %>

test:
  <<: *default
  database: <%= ENV['POSTGRES_TEST_DB'] %>
  username: <%= ENV["USER_NAME"] %>
  password: <%= ENV["PASSWORD"] %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

